---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-example-com-my-domain-v1-wordpress
  failurePolicy: Fail
  name: mwordpress-v1.kb.io
  rules:
  - apiGroups:
    - example.com.my.domain
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - wordpresses
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-example-com-my-domain-v1-wordpress
  failurePolicy: Fail
  name: vwordpress-v1.kb.io
  rules:
  - apiGroups:
    - example.com.my.domain
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - wordpresses
  sideEffects: None
