name: Kubebuilder Update

on:
  schedule:
    - cron: '0 6 * * 1'  # Weekly automation
  workflow_dispatch:       # Manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Kubebuilder
        run: |
          curl -L -o kubebuilder "https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)"
          chmod +x kubebuilder
          sudo mv kubebuilder /usr/local/bin/

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run kubebuilder alpha update
        run: |
          kubebuilder alpha update --force --from-version v4.5.2 || echo "Update skipped or failed — continuing."

      - name: Detect merge branch
        id: check_branch
        run: |
          MERGE_BRANCH=$(git branch --show-current)
          echo "Current branch: $MERGE_BRANCH"
          echo "branch=$MERGE_BRANCH" >> $GITHUB_OUTPUT

          if [[ ! "$MERGE_BRANCH" =~ merge ]]; then
            echo "No merge branch created — skipping push and PR."
            exit 1
          fi

      - name: Push merge branch
        run: |
          git push origin "${{ steps.check_branch.outputs.branch }}" --force

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ steps.check_branch.outputs.branch }}
          title: "chore: update Kubebuilder scaffolding"
          body: |
            This PR was created automatically using `kubebuilder alpha update --force`.

            Please review the generated changes and merge if appropriate.
          commit-message: |
            chore: update Kubebuilder scaffolding

            This update was generated by `kubebuilder alpha update --force`.
          delete-branch: true
          labels: kubebuilder-update

      - name: Log PR details
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request #${{ steps.cpr.outputs.pull-request-number }}"
          echo "URL: ${{ steps.cpr.outputs.pull-request-url }}"
