name: Alpha Update
# Alpha update requires write access to the repository to create a branch
# with the update files and allow you to open a pull request using the
# link provided in the issue. The branch created will be named in the
# format kubebuilder-update-from-<from-version>-to-<to-version> by default.
# To protect your codebase, please ensure that you have branch protection rules
# configured for your main branches. This will guarantee that no one can bypass a review
# and push directly to a branch like 'main'.
permissions:
  contents: write
  issues: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2" # Every Tuesday at 00:00 UTC

jobs:
  alpha-update:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Step 1: Checkout the repository.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Step 2: Configure Git to create commits with the GitHub Actions bot.
      - name: Configure Git
        run: |
          git config --global user.name
