name: Kubebuilder Update

on:
  schedule:
    - cron: '0 6 * * 1'  # Weekly automation
  workflow_dispatch:       # Manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Kubebuilder
        run: |
          curl -L -o kubebuilder "https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)"
          chmod +x kubebuilder
          sudo mv kubebuilder /usr/local/bin/

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run kubebuilder alpha update
        run: |
          kubebuilder alpha update --force --from-version v4.5.2 || echo "Update skipped or failed — continuing."

      - name: Detect merge branch
        id: check_branch
        run: |
          MERGE_BRANCH=$(git branch --show-current)
          echo "Current branch: $MERGE_BRANCH"
          echo "branch=$MERGE_BRANCH" >> $GITHUB_OUTPUT

          if [[ ! "$MERGE_BRANCH" =~ merge ]]; then
            echo "No merge branch created — skipping push and PR."
            exit 1
          fi

      - name: Push merge branch
        run: |
          git push origin "${{ steps.check_branch.outputs.branch }}" --force

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create pull request via REST API
        id: create_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating PR for branch: ${{ steps.check_branch.outputs.branch }}"
          PR_DATA=$(jq -n \
            --arg title "chore: update Kubebuilder scaffolding" \
            --arg body "This PR was created automatically using \`kubebuilder alpha update --force\`. Please review the changes and merge." \
            --arg head "${{ steps.check_branch.outputs.branch }}" \
            --arg base "main" \
            '{title: $title, head: $head, base: $base, body: $body}')

          HTTP_RESPONSE=$(curl -s -w "%{http_code}" -o response.json -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "$PR_DATA")

          if [[ "$HTTP_RESPONSE" != "201" ]]; then
            echo "Failed to create PR:"
            cat response.json
            exit 1
          fi

          PR_NUMBER=$(jq '.number' response.json)
          echo "PR created: #$PR_NUMBER"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Add PR label
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.create_pr.outputs.pr_number }}/labels \
            -d '{"labels": ["kubebuilder-update"]}'
