name: Alpha Update (with AI summary)

permissions:
  contents: write
  issues: write
  pull-requests: write
  models: read  # Necessary permission

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2" # Every Tuesday at 00:00 UTC

jobs:
  alpha-update:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Configure Git
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install Kubebuilder
      run: |
        git clone --depth 1 --branch master \
          https://github.com/kubernetes-sigs/kubebuilder.git /tmp/kubebuilder
        cd /tmp/kubebuilder
        make build
        sudo cp bin/kubebuilder /usr/local/bin/
        kubebuilder version

    - name: Run kubebuilder alpha update
      run: |
        kubebuilder alpha update \
          --force \
          --restore-path .github/workflows \
          --push \
          --output-branch test-ai-update-test-53 \
          --from-version v4.5.2 \
          --open-gh-issue

    - name: Create patch of last commit # Users may want to extract other info
      run: |
        git show HEAD > update.patch

    - name: Prepare model prompt # Room for prompt engineering
      run: |
        cat > prompt.txt <<'EOF'
        Start by stating that this summary is AI generated and can contain errors.
        You are a concise update summarizer for an automated Kubebuilder scaffold update.
        Analyze the patch and write a GitHub Issue comment that explains what changed.
        Scan the patch for Git conflict markers (<<<<<<<, =======, >>>>>>>). For each conflict:
        Explain what caused the conflict.
        How to properly resolve them.
        Inform the user about the recommended next steps.
        Constraints: Markdown only, no raw diff snippets.

        ---- DIFF BELOW ----
        EOF
        cat update.patch >> prompt.txt

    - name: Generate summary with GitHub Models # Room for parameters tuning
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -o pipefail
        jq -Rs '
        {
          model: "openai/gpt-4o",
          messages: [
            { "role": "user", "content": . }
          ],
          max_tokens: 4000,
          temperature: 0
        }' < prompt.txt \
        | curl -sS https://models.github.ai/inference/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            --data @- \
        | jq -r '.choices[0].message.content' > COMMENT.md

    - name: Determine update issue number
      id: find-issue
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        out=$(gh issue list --state open --limit 100 --json number,title,createdAt)
        issue_number=$(echo "$out" | jq -r '
          sort_by(.createdAt)
          | map(select(.title|test("^\\[Action Required\\] Upgrade the Scaffold: v[0-9.]+ -> v[0-9.]+$")))
          | last.number // empty
        ')
        echo "issue_number=${issue_number}" >> "$GITHUB_OUTPUT"

    - name: Post comment to issue
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue comment "${{ steps.find-issue.outputs.issue_number }}" --body-file COMMENT.md